# Production overrides
server:
  port: ${PORT:8080}

logging:
  level:
    root: WARN
    com.example.sample_starter: INFO

spring:
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
  sql:
    init:
      mode: never
  # datasource:
  #   url: ${DB_URL}
  #   username: ${DB_USERNAME}
  #   password: ${DB_PASSWORD}

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false
