# Local development overrides
server:
  port: 8080

logging:
  level:
    root: INFO
    com.example.buildpro: DEBUG

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/buildpro
    username: postgres
    password: Hertzberger7793
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate #update
    show-sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: never #always
